# Generated by Django 4.0.6 on 2022-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_alter_comentario_fechacomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog/imagenes'),
        ),
    ]
