# Generated by Django 4.0.6 on 2022-08-24 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejemplo', '0012_alter_noticia_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL)),
                ('posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='ejemplo.noticia')),
            ],
        ),
    ]
