# Generated by Django 4.0.6 on 2022-08-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0014_alter_comentarioposteo_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioposteo',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
