# Generated by Django 4.0.6 on 2022-08-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejemplo', '0015_alter_comentarioposteo_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioposteo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioposteo',
            name='cuerpo',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comentarioposteo',
            name='posteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplo.noticia'),
        ),
    ]
